### ISSUE TITLE
Can't update to new version 

### ISSUE THREAD

**Issue by Cassie724** [novvvels/WuxiaNovvvels#7]
I made a mistake when updating to the new version, I think I clicked no when asked a question and now I can't update the app anymore it keeps showing app not installed. 

The current version I have doesn't update books anymore, I tried deleting the books and downloading it back but when I open the book it doesn't show anything, it's completely blank. Please fix these issues for me. Thanks. 

I use TECNO K9 (Tecno spark plus)  version 7.0

**Comment by novvvels** [comment]
Hello,
The update books issue is fixed .please try to reload the book.

**Comment by Cassie724** [comment]
Well it worked for a while but there's a particular book that isn't updating it's titled "it's not easy to be a man after traveling to the future by Madam R". Please work on this and also I still can't update to the new version of Wuxia

**Comment by nagicris1003** [comment]
All the books are not updating. What is the matter?

**Comment by Cassie724** [comment]
It seems their servers are still having errors cause even my books stopped updating day's ago I felt it will be worked on so I didn't complain but it still hasn't.... So can you guys please work on it? And I still can't update to the new version of wuxia

**Comment by novvvels** [comment]
@Cassie724 @nagicris1003 Sorry , these days we add some more book , and I bring a bug into the server  which caused that the book not updating.
I just fixed it. please check it. if it still happen, please comment it here.

**Comment by Cassie724** [comment]
It's updating thanks a lot

**Comment by Cassie724** [comment]
Hey guys, it worked for a day then stop, it never works for long...can you
guys work on it? Oh and non of my books are updating not just one of them.
Thanks guys.

**Comment by novvvels** [comment]
@Cassie724 Sorry，my fault~. now fixing it.

**Comment by Cassie724** [comment]
Hello, how are you guys doing?... Huh... I wanted to ask you to please
upload some books I wanted like.... Rebirth to a Military Marriage: Good
Morning Chief by Brocade Star of Love, The Emperor's Daughter by YUNSUL,
Accidentally Married a Fox God by MoonBirth, and Mr. Tycoon's daring wife
by Xincerely. I don't know if it's proper to do this but I hope you guys
can help me out with these books. Thanks a lot and sorry for any
inconvenience I might cause you.

**Comment by novvvels** [comment]
@Cassie724 Hello, we are busy on a new version which will completely resolve this kind of issue.
Next version, it has a brand new mechanism to get the new chapter. 
Currently the source of these novels is not stable, so it often miss new chapters.

**Comment by Cassie724** [comment]
Oh....alright thanks.... Am looking forward to it... Oh, please ensure that
this version can be downloaded and installed cause I still can't install
the 10th version. Thanks alot for the hardwork guy's really appreciate it .

**Comment by novvvels** [comment]
@Cassie724 When the beta version is ready, we can provide it to you for preview ^_^

**Comment by Cassie724** [comment]
Sure, I would love to. Thanks alot

**Comment by Cassie724** [comment]
Am sorry for disturbing again.... But there's a couple of books I was
reading that became blank half way through the book, it's called....
Rebirth of the godly prodigal by Chen Ji Tang Hong Dou and The Beautiful
Wife of the Whirlwind Marriage by Bath Robey....please can you guys fix
it....I would really appreciate it

**Comment by novvvels** [comment]
@Cassie724 hello ,we'd like to start the internal testing of our next version. would you mind send us a email , then we will send you the test apk link. and we also need the book list which you are reading.

**Comment by Cassie724** [comment]
Yes!!!.... That's nice, thanks alot. Here's my booklist.

It's not easy to be a man after traveling to the future, King of God's,
Library of Heaven's Path, His genius wife is a superstar, The Beautiful
Wife of the Whirlwind Marriage, Rebirth of the Godly Prodigal, Superstars
of Tomorrow, I'm really a Superstar, National school Prince is a Girl, His
Peasant Wife: Yoa Ling, Spirit Realm, Endless Pampering, Little Miss Devil:
The President Mischievous Wife, Ancient Godly Monarch, Cultivation Chat
Group, The Beautiful Time Spent With You, God of Slaughter, Evil Emperor's
Wild Consort, My Youth Began With Him, Flowers Bloom a Battlefield, Lord
Xue Yong, Mr CEO spoil me 100 percent, A Star Reborn: The Queen's Return,
Warning! Tsundere, Shift! The side character, Swallowed Star, The Evil
consort above an evil king, The most loving marriage in history, If  deep
sea forgets, One birth two treasures: the billionaire's sweet love, The
rebirth of the malicious empress, The employed empress, Dragon Kings
Son-In-Law, The Strongest Gene,  Immortal Mortal, A mistaken marriage, The
famous painter is the ceo wife, Oukoku e Tsuzuku.

Thanks for giving me the chance.

**Comment by novvvels** [comment]
@Cassie724 please send your email address to wuxianovvvels@hotmail.com, we will send your the link by email

**Comment by Cassie724** [comment]
Hello....how you guys doing, I got a new phone so I downloaded the 2.1
version that was sent to my email, it's the beta version, but I discovered
that I can't search for books and add them cuz it won't show, even when I
add books from the bookstore and I decide to search for it later I won't
find it. Can you guys work on it? Or tell me where I can download the
upgrade version. Thank you very much.

**Comment by novvvels** [comment]
@Cassie724 We disabled 2.1version search function as it's internal testing. I suggestion you use 2.0 verison which is still work fine. I will put the 2.0 version in  Github Release.
